# Generated by Django 5.2.5 on 2025-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst',
            field=models.FloatField(default=0),
        ),
    ]
