# Generated by Django 5.2.5 on 2025-10-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_cgst_bill_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
