# Generated by Django 5.2.5 on 2025-10-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
