# Generated by Django 5.2.5 on 2025-10-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
