# Generated by Django 5.2.5 on 2025-10-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bill_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='time',
        ),
    ]
